# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/MappedIn/podspec.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'MappedIn', '1.13.0'
  pod 'SiamPiwatIndoorMapSDK', :path => '../'
end
